# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12200befeb88258fc2adfaa189aff38ffd9d4eb41c5dee040ad3d73b02bc4fbfe19d";
    path = fetchzip {
      url = "https://github.com/gingerfocus/thermit/archive/68c5a7b810f79e11d296e2f0593649c5b1d6ce91.tar.gz";
      hash = "sha256-m5JODm2dB/vUbTw+ZmLMhgsrZu/mtjRQrQG6TfQzeOg=";
    };
  }
]
