# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AABdRQgCigs7KLUb8QxQk1Pi15kpIDYtYvMoXpMGb";
    path = fetchgit {
      url = "https://github.com/LuaJIT/LuaJIT";
      rev = "538a82133ad6fddfd0ca64de167c4aca3bc1a2da";
      hash = "sha256-NfxPe0MlE7X7YzVeN7jeHeOJ0j9NOUbQv7y3rcyc1Nk=";
    };
  }
  {
    name = "graphi-0.1.0-gpZJC2RdAAA3kOAu3V5KLmB6yY2eeoOksS9uDl7Hldqh";
    path = fetchzip {
      url = "https://github.com/gingerfocus/graphi/archive/e2e08244a1c55db5df95db088158901280c68f6b.tar.gz";
      hash = "sha256-5dU698YGFtofYooOGhk98RHimWIlfuqPYYbrn6Buh/M=";
    };
  }
  {
    name = "libxev-0.0.0-86vtc4b1EgCl0Kvo2Ixmjfl5PgAaJmvCXRIn_n89nCaR";
    path = fetchzip {
      url = "https://github.com/mitchellh/libxev/archive/5647630d7bff969414a0edc24c03c30aff34b101.tar.gz";
      hash = "sha256-nlJzFS/4BdKUmBwacdvEmFRn+E8YWnD6R/c2OcStd7w=";
    };
  }
  {
    name = "luajit_build-1.1.1-HFjoU2o7AABxdkMbYn4spnXyUICP5lnM9bqhx83JFAuw";
    path = fetchzip {
      url = "https://github.com/sackosoft/zig-luajit-build/archive/205386cedc14c919eaed387f9c12156c3ef3d43c.tar.gz";
      hash = "sha256-Z/aE7zJTIGQtHl8mhmzUC/yMag4DE839jIZip+UWqLw=";
    };
  }
  {
    name = "thermit-0.1.0-wTQBCK6xAACeA7Jn4eYRowWfeV8KT94NaNQs-f62JTfd";
    path = fetchzip {
      url = "https://github.com/gingerfocus/thermit/archive/5a78059eea5ff1b2dd80059128d40d04ad5cf060.tar.gz";
      hash = "sha256-Y1tFmjKG6tZJzXMbRowb5wNV2qGBo4tsOmAfh8fBIpE=";
    };
  }
]
