# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220fb80d5cadb5dc38ed605a9748ba4549f16b0b25e480fff2a2ceb30e1fe760667";
    path = fetchzip {
      url = "https://github.com/gingerfocus/thermit/archive/00117a6864a1e9e2ad746c1d123470965f7992db.tar.gz";
      hash = "sha256-KUfowgavYW/k3yzuCo6j+15o13f01jldU/2PRgpJqSM=";
    };
  }
]
