name: Zig Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - name: test
      run: zig build test --summary all
    - name: build
      run: zig build run -- -R /dev/stdout README.md
