name: Zig PR Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v2
    - name: build
      run: zig build -Dstatic=true -Dwindowing=false
    # - name: test
    #   run: zig build test -Dstatic=true -Dwindowing=false
